# Generated by Django 5.0.3 on 2024-03-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('preco', models.DecimalField(decimal_places=2, default=99.99, max_digits=15)),
                ('ano_edicao', models.IntegerField()),
                ('autor', models.CharField(max_length=120)),
                ('genero', models.CharField(max_length=120)),
                ('cod_ISBN', models.CharField(max_length=13)),
                ('idioma', models.CharField(max_length=120)),
                ('num_paginas', models.IntegerField()),
                ('editora', models.CharField(max_length=120)),
            ],
        ),
    ]
